### ISSUE TITLE
New Transport Font used in examples

### ISSUE THREAD

**Issue by charlesrt** [abbott567/DWP_patterns#5]
We are still using the New Transport font in the example snippets. Whilst this gives a true representation of how patterns will appear on GOV.UK, do we need to switch to our alt font stack until licensing is finalised?

**Comment by abbott567** [comment]
Hi Charles, 

I was told the examples should be GDS Transport. I assume its because the examples they were taken from are hosted on GOVUK?

Cheers,
C
_____________________

Craig Abbott
Interaction Designer DWP

**Comment by charlesrt** [comment]
Thanks Craig. As long as someone has taken responsibility for the decision against licensing - even though the examples mimic GOV.UK, the DWP pattern library isn't hosted on a GOV.UK domain which is the condition of the license as we know it - https://designnotes.blog.gov.uk/2015/03/11/can-i-use-the-gov-uk-fonts/

Technically, this is an issue with the whole prototype kit we use.

Do we need to switch to our alt font stack until GDS confirm what the full licensing conditions are?

**Comment by charlesrt** [comment]
Posted in the design group for clarification - https://groups.google.com/a/digital.cabinet-office.gov.uk/forum/#!topic/digital-service-designers/uSppBuHjslQ
